In [1]:
import yfinance as yf

In [6]:
btc = yf.Ticker("BTC-USD")

In [7]:
print(btc)

yfinance.Ticker object <BTC-USD>

In [8]:
btc.info

{'name': 'Bitcoin',
 'startDate': 1278979200,
 'description': 'Bitcoin (BTC) is a cryptocurrency launched in 2010. Users are able to generate BTC through the process of mining. Bitcoin has a current supply of 19,780,268. The last known price of Bitcoin is 79,482.63227078 USD and is up 3.78 over the last 24 hours. It is currently trading on 11797 active market(s) with $48,397,882,908.02 traded over the last 24 hours. More information can be found at https://bitcoin.org/.',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 80444.125,
 'open': 80444.125,
 'dayLow': 80444.125,
 'dayHigh': 80772.164,
 'regularMarketPreviousClose': 80444.125,
 'regularMarketOpen': 80444.125,
 'regularMarketDayLow': 80444.125,
 'regularMarketDayHigh': 80772.164,
 'volume': 82735874048,
 'regularMarketVolume': 82735874048,
 'averageVolume': 32203621221,
 'averageVolume10days': 49714898305,
 'averageDailyVolume10Day': 49714898305,
 'marketCap': 1591431004160,
 'fiftyTwoWeekLow': 34948.5,
 'fiftyTwoWeekHigh': 80772.164,
 'fiftyDayAverage': 66521.8,
 'twoHundredDayAverage': 63707.324,
 'currency': 'USD',
 'fromCurrency': 'BTC',
 'toCurrency': 'USD=X',
 'lastMarket': 'CoinMarketCap',
 'coinMarketCapLink': 'https://coinmarketcap.com/currencies/bitcoin',
 'volume24Hr': 82735874048,
 'volumeAllCurrencies': 82735874048,
 'circulatingSupply': 19780564,
 'exchange': 'CCC',
 'quoteType': 'CRYPTOCURRENCY',
 'symbol': 'BTC-USD',
 'underlyingSymbol': 'BTC-USD',
 'shortName': 'Bitcoin USD',
 'longName': 'Bitcoin USD',
 'firstTradeDateEpochUtc': 1410912000,
 'timeZoneFullName': 'UTC',
 'timeZoneShortName': 'UTC',
 'uuid': '74397779-1589-3270-8c45-b7f1a7345b3a',
 'messageBoardId': 'finmb_BTC_CCC',
 'trailingPegRatio': None}

In [9]:
btc.history(period="max")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2014-09-17 00:00:00+00:00,465.864014,468.174011,452.421997,457.334015,21056800,0.0,0.0
2014-09-18 00:00:00+00:00,456.859985,456.859985,413.104004,424.440002,34483200,0.0,0.0
2014-09-19 00:00:00+00:00,424.102997,427.834991,384.532013,394.795990,37919700,0.0,0.0
2014-09-20 00:00:00+00:00,394.673004,423.295990,389.882996,408.903992,36863600,0.0,0.0
2014-09-21 00:00:00+00:00,408.084991,412.425995,393.181000,398.821014,26580100,0.0,0.0
...,...,...,...,...,...,...,...
2024-11-06 00:00:00+00:00,69358.500000,76460.156250,69322.031250,75639.078125,118592653963,0.0,0.0
2024-11-07 00:00:00+00:00,75637.085938,76943.117188,74480.421875,75904.859375,63467654989,0.0,0.0
2024-11-08 00:00:00+00:00,75902.835938,77252.750000,75648.742188,76545.476562,55176858003,0.0,0.0
2024-11-09 00:00:00+00:00,76556.187500,76932.765625,75773.789062,76778.867188,29009480361,0.0,0.0
2024-11-11 00:00:00+00:00,80444.125000,80772.164062,80444.125000,80476.320312,82739249152,0.0,0.0

In [10]:
eth = yf.Ticker("ETH-USD")

In [11]:
eth.info

{'twitter': '"https://twitter.com/ethereum"',
 'name': 'Ethereum',
 'startDate': 1438905600,
 'description': 'Ethereum (ETH) is a cryptocurrency . Ethereum has a current supply of 120,423,059.36814076. The last known price of Ethereum is 3,190.21762975 USD and is up 4.78 over the last 24 hours. It is currently trading on 9506 active market(s) with $33,143,802,871.71 traded over the last 24 hours. More information can be found at https://www.ethereum.org/.',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 3187.5813,
 'open': 3187.5813,
 'dayLow': 3186.2583,
 'dayHigh': 3200.409,
 'regularMarketPreviousClose': 3187.5813,
 'regularMarketOpen': 3187.5813,
 'regularMarketDayLow': 3186.2583,
 'regularMarketDayHigh': 3200.409,
 'volume': 47517958144,
 'regularMarketVolume': 47517958144,
 'averageVolume': 15876569846,
 'averageVolume10days': 23904063015,
 'averageDailyVolume10Day': 23904063015,
 'marketCap': 384194707456,
 'fiftyTwoWeekLow': 1910.4454,
 'fiftyTwoWeekHigh': 4092.2842,
 'fiftyDayAverage': 2567.6892,
 'twoHundredDayAverage': 2955.1965,
 'currency': 'USD',
 'fromCurrency': 'ETH',
 'toCurrency': 'USD=X',
 'lastMarket': 'CoinMarketCap',
 'coinMarketCapLink': 'https://coinmarketcap.com/currencies/ethereum',
 'volume24Hr': 47517958144,
 'volumeAllCurrencies': 47517958144,
 'circulatingSupply': 120421256,
 'exchange': 'CCC',
 'quoteType': 'CRYPTOCURRENCY',
 'symbol': 'ETH-USD',
 'underlyingSymbol': 'ETH-USD',
 'shortName': 'Ethereum USD',
 'longName': 'Ethereum USD',
 'firstTradeDateEpochUtc': 1510185600,
 'timeZoneFullName': 'UTC',
 'timeZoneShortName': 'UTC',
 'uuid': 'c32b80a9-b35b-3c25-9500-7c2b54dfcc04',
 'messageBoardId': 'finmb_ETH_CCC',
 'trailingPegRatio': None}

In [12]:
eth.history(period="max")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2017-11-09 00:00:00+00:00,308.644989,329.451996,307.056000,320.884003,893249984,0.0,0.0
2017-11-10 00:00:00+00:00,320.670990,324.717987,294.541992,299.252991,885985984,0.0,0.0
2017-11-11 00:00:00+00:00,298.585999,319.453003,298.191986,314.681000,842300992,0.0,0.0
2017-11-12 00:00:00+00:00,314.690002,319.153015,298.513000,307.907990,1613479936,0.0,0.0
2017-11-13 00:00:00+00:00,307.024994,328.415009,307.024994,316.716003,1041889984,0.0,0.0
...,...,...,...,...,...,...,...
2024-11-06 00:00:00+00:00,2422.539307,2743.964111,2421.812988,2724.169189,41887574364,0.0,0.0
2024-11-07 00:00:00+00:00,2724.005859,2918.744385,2701.590820,2895.585449,35352318438,0.0,0.0
2024-11-08 00:00:00+00:00,2895.597900,2983.744873,2889.484375,2962.296631,32303261101,0.0,0.0
2024-11-09 00:00:00+00:00,2962.791016,3156.366211,2957.182373,3131.144531,29210133088,0.0,0.0
2024-11-11 00:00:00+00:00,3187.581299,3200.408936,3186.258301,3192.855469,47512297472,0.0,0.0